language: cpp

sudo: false

compiler:
  - gcc
  - clang

script: ./autosetup.sh && ./configure && make

addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - qtbase5-dev
    - qtbase5-dev-tools
    - qttools5-dev-tools
    - libqt5opengl5-dev

